services:
  db:
    image: postgres:15
    hostname: ${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  testdb:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data/
    command:
      - "postgres"
      - "-c"
      - "fsync=off"
      - "-c"
      - "shared_buffers=1024MB"
      - "-c"
      - "synchronous_commit=off"
      - "-c"
      - "full_page_writes=off"
      - "-c"
      - "log_statement=all"
      - "-c"
      - "max_connections=1000"
    ports:
      - "5433:5432"

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    command: ["-path", "/migrations/", "-database", "${DATABASE_URL}", "up"]

  smtp:
    image: rnwood/smtp4dev:v3
    hostname: ${SMTP_HOST}
    ports:
      - ${SMTP_WEB_PORT}:80
      - ${SMTP_PORT}:25
    volumes:
      - smtp4dev-data:/smtp4dev

volumes:
  postgres-data:
  smtp4dev-data:
