GET http://localhost:4000/v1/healthcheck HTTP/1.1

### User signup. Requests verificaiton token.
POST http://localhost:4000/v1/tokens/verification/registration HTTP/1.1
content-type: application/json

{
    "email": "test@example.com"
}

### Use verificaiton token to create an account
POST http://localhost:4000/v1/users HTTP/1.1
content-type: application/json

{
    "email": "test@example.com",
    "password": "super_secret_password",
    "token": "YVG2SMLOMLKBBFWG75CCHQFW3E"
}

### Request authentication token in exchange for credentials
POST http://localhost:4000/v1/tokens/authentication HTTP/1.1
content-type: application/json

{
    "email": "test@example.com",
    "password": "super_secret_password"
}

### Use auth token to get user information
GET http://localhost:4000/v1/users/me HTTP/1.1
Authorization: Bearer GHVJ6IDRYTSOUGE2XGQQBVNWGA

### Request a verification token to change email
POST http://localhost:4000/v1/tokens/verification/email-change HTTP/1.1
Authorization: Bearer GHVJ6IDRYTSOUGE2XGQQBVNWGA
content-type: application/json

{
    "email": "updated@domain.org"
}

### Update user with new email address
PUT http://localhost:4000/v1/users/me HTTP/1.1
Authorization: Bearer GHVJ6IDRYTSOUGE2XGQQBVNWGA
content-type: application/json

{
    "email": "updated@domain.org",
    "token": "6PYCCWVMZRZVFLGSXQTZ6F6QLQ"
}

### Check if email is updated
GET http://localhost:4000/v1/users/me HTTP/1.1
Authorization: Bearer GHVJ6IDRYTSOUGE2XGQQBVNWGA

### Request a password reset
POST http://localhost:4000/v1/tokens/verification/password-reset HTTP/1.1
content-type: application/json

{
    "email": "updated@domain.org"
}

### Reset password
PUT http://localhost:4000/v1/users/password HTTP/1.1
content-type: application/json

{
    "password": "new_secret_password",
    "token": "LL6MNAVQNFULUQWTDXRO6COFHY"
}

### Request authentication token in exchange for new credentials
POST http://localhost:4000/v1/tokens/authentication HTTP/1.1
content-type: application/json

{
    "email": "updated@domain.org",
    "password": "new_secret_password"
}

### Use new auth token to get user information
GET http://localhost:4000/v1/users/me HTTP/1.1
Authorization: Bearer FO23VDWEN7WYIFUHKEWKKINPNI