GET http://localhost:4000/v1/healthcheck HTTP/1.1

### User signup. Requests verificaiton token.
POST http://localhost:4000/v1/tokens/verification/registration HTTP/1.1
content-type: application/json

{
    "email": "test@example.com"
}

### Use verificaiton token to create an account
POST http://localhost:4000/v1/users HTTP/1.1
content-type: application/json

{
    "email": "test@example.com",
    "password": "super_secret_password",
    "token": "UUIRLHPAJ67ZQSJRZYNXFQPXW4"
}

### Request authentication token in exchange for credentials
POST http://localhost:4000/v1/tokens/authentication HTTP/1.1
content-type: application/json

{
    "email": "test@example.com",
    "password": "super_secret_password"
}

### Use auth token to get user information
GET http://localhost:4000/v1/users/me HTTP/1.1
Authorization: Bearer TCRWPOEZKY5YC7XGMJVMNZLTYE

### Request a verification token to change email
POST http://localhost:4000/v1/tokens/verification/email-change HTTP/1.1
Authorization: Bearer TCRWPOEZKY5YC7XGMJVMNZLTYE
content-type: application/json

{
    "email": "updated@domain.org"
}

### Update user with new email address
PUT http://localhost:4000/v1/users/me HTTP/1.1
Authorization: Bearer TCRWPOEZKY5YC7XGMJVMNZLTYE
content-type: application/json

{
    "email": "updated@domain.org",
    "token": "IEJDVIX5LEZQW2TMX24737O6KY"
}

### Check if email is updated
GET http://localhost:4000/v1/users/me HTTP/1.1
Authorization: Bearer TCRWPOEZKY5YC7XGMJVMNZLTYE

### Request a password reset
POST http://localhost:4000/v1/tokens/verification/password-reset HTTP/1.1
content-type: application/json

{
    "email": "updated@domain.org"
}

### Reset password
PUT http://localhost:4000/v1/users/password HTTP/1.1
content-type: application/json

{
    "password": "new_secret_password",
    "token": "MFELQNRXBDWCMXTYBEABLURIMU"
}

### Request authentication token in exchange for new credentials
POST http://localhost:4000/v1/tokens/authentication HTTP/1.1
content-type: application/json

{
    "email": "updated@domain.org",
    "password": "new_secret_password"
}

### Use new auth token to get user information
GET http://localhost:4000/v1/users/me HTTP/1.1
Authorization: Bearer IEWKOBF5INWGAFEEBXMHYHYPTM