FROM golang:1.24.1-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY migrations/ ./migrations/

COPY lib/ ./lib/

COPY api/ ./api/

WORKDIR /app/api

CMD ["air", "-c", "air.toml"]